name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.20.3
  - netCDF4=1.6.0
  - matplotlib=3.4.3
  - pandas=1.3.4
  - proplot=0.9.5
  - pyproj=3.3.0
  - scipy=1.7.1
  - proplot=0.9.5
