name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - mpl_toolkits
  - netCDF4
  - os
  - scipy
  - pyproj 
  - astropy 
  - h5py 
  - itertools
  - sys
  - copy
  - pandas
  - proplot 
  - cartopy
