name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - psutil
  - toolz
  - netCDF4
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - pyproj
  - scipy
