name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.9.18
  - numpy=1.20.3
  - psutil
  - toolz
  - netCDF4=1.6.0
  - matplotlib
  - dill
  - pandas=1.3.4
  - partd
  - bokeh
  - dask
  - pyproj=3.3.0
  - scipy=1.7.1
  - proplot=0.9.5
  - shapely=1.7.1
  - pyshp=2.1
  - cartopy=0.22.0
