name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.4
  - numpy=1.20.3
  - matplotlib=3.4.3
  - mpl_toolkits
  - netCDF4=1.6.0
  - os
  - scipy=1.7.1
  - pyproj=3.3.0 
  - sys
  - pandas=1.3.4
  - proplot=0.9.5
  - cartopy=0.22.0
